// game/src/components/DialogueBox.tsx
// 🎮 Dialogue Box Component 💬✨
import { useState, useEffect } from 'react';
import type { DialogueLine } from '../types';
import './DialogueBox.css';

interface DialogueBoxProps {
  dialogue: DialogueLine[];
  onComplete: () => void;
}

export function DialogueBox({ dialogue, onComplete }: DialogueBoxProps) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [displayedText, setDisplayedText] = useState('');
  const [isTyping, setIsTyping] = useState(true);

  const currentLine = dialogue[currentIndex];
  const isLastLine = currentIndex === dialogue.length - 1;

  // Typewriter effect ✍️
  useEffect(() => {
    setDisplayedText('');
    setIsTyping(true);
    let charIndex = 0;
    const text = currentLine?.text || '';
    
    const timer = setInterval(() => {
      if (charIndex < text.length) {
        setDisplayedText(text.slice(0, charIndex + 1));
        charIndex++;
      } else {
        setIsTyping(false);
        clearInterval(timer);
      }
    }, 25);

    return () => clearInterval(timer);
  }, [currentIndex, currentLine?.text]);

  const handleClick = () => {
    if (isTyping) {
      // Skip to end of current text
      setDisplayedText(currentLine?.text || '');
      setIsTyping(false);
    } else if (isLastLine) {
      // Dialogue complete
      onComplete();
    } else {
      // Next line
      setCurrentIndex(prev => prev + 1);
    }
  };

  const getEmotionClass = (emotion?: string) => {
    switch (emotion) {
      case 'happy': return 'emotion-happy';
      case 'sad': return 'emotion-sad';
      case 'angry': return 'emotion-angry';
      case 'mysterious': return 'emotion-mysterious';
      default: return '';
    }
  };

  if (!currentLine) return null;

  return (
    <div className="dialogue-container" onClick={handleClick}>
      <div className={`dialogue-box ${getEmotionClass(currentLine.emotion)}`}>
        <div className="speaker-name">
          {currentLine.speaker}
        </div>
        <div className="dialogue-text">
          {displayedText}
          {isTyping && <span className="cursor">▌</span>}
        </div>
        <div className="dialogue-hint">
          {isTyping ? '⏭️ Click to skip' : isLastLine ? '✨ Click to continue' : '➡️ Click for next'}
        </div>
      </div>
      <div className="dialogue-progress">
        {dialogue.map((_, i) => (
          <span 
            key={i} 
            className={`progress-dot ${i <= currentIndex ? 'active' : ''}`}
          />
        ))}
      </div>
    </div>
  );
}

// game/src/components/DialogueBox.vue
<!-- 🎮 Dialogue Box Component 💬✨ -->
<template>
  <div class="dialogue-container" @click="handleClick">
    <div class="dialogue-box" :class="getEmotionClass(currentLine?.emotion)">
      <div class="speaker-name">
        {{ currentLine?.speaker }}
      </div>
      <div class="dialogue-text">
        {{ displayedText }}
        <span v-if="isTyping" class="cursor">▌</span>
      </div>
      <div class="dialogue-hint">
        {{ isTyping ? '⏭️ Click to skip' : isLastLine ? '✨ Click to continue' : '➡️ Click for next' }}
      </div>
    </div>
    <div class="dialogue-progress">
      <span 
        v-for="(_, i) in dialogue" 
        :key="i" 
        class="progress-dot"
        :class="{ active: i <= currentIndex }"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from 'vue'
import type { DialogueLine } from '../types'

interface Props {
  dialogue: DialogueLine[]
}

const props = defineProps<Props>()
const emit = defineEmits<{
  complete: []
}>()

const currentIndex = ref(0)
const displayedText = ref('')
const isTyping = ref(true)
let timer: ReturnType<typeof setInterval> | null = null

const currentLine = computed(() => props.dialogue[currentIndex.value])
const isLastLine = computed(() => currentIndex.value === props.dialogue.length - 1)

// Typewriter effect ✍️
const startTypewriter = () => {
  displayedText.value = ''
  isTyping.value = true
  let charIndex = 0
  const text = currentLine.value?.text || ''
  
  if (timer) clearInterval(timer)
  
  timer = setInterval(() => {
    if (charIndex < text.length) {
      displayedText.value = text.slice(0, charIndex + 1)
      charIndex++
    } else {
      isTyping.value = false
      if (timer) clearInterval(timer)
    }
  }, 25)
}

// Watch for dialogue changes and restart typewriter
watch([currentIndex, () => props.dialogue], () => {
  startTypewriter()
}, { immediate: true })

onUnmounted(() => {
  if (timer) clearInterval(timer)
})

const handleClick = () => {
  if (isTyping.value) {
    // Skip to end of current text
    displayedText.value = currentLine.value?.text || ''
    isTyping.value = false
    if (timer) clearInterval(timer)
  } else if (isLastLine.value) {
    // Dialogue complete
    currentIndex.value = 0
    emit('complete')
  } else {
    // Next line
    currentIndex.value++
  }
}

const getEmotionClass = (emotion?: string): string => {
  switch (emotion) {
    case 'happy': return 'emotion-happy'
    case 'sad': return 'emotion-sad'
    case 'angry': return 'emotion-angry'
    case 'mysterious': return 'emotion-mysterious'
    default: return ''
  }
}
</script>

<style src="./DialogueBox.css"></style>
