// game/src/components/StatusBar.vue
<!-- 📊 Status Bar Component ✨ -->
<template>
  <div class="status-bar">
    <div class="status-left">
      <span class="location-badge">
        📍 {{ formatLocation(sceneName) }}
      </span>
      <span 
        class="stability-badge" 
        :style="{ 
          color: gameState.driftStability > 70 ? '#22c55e' : gameState.driftStability > 30 ? '#f59e0b' : '#ef4444' 
        }"
      >
        🌀 Drift: {{ gameState.driftStability }}%
      </span>
    </div>
    
    <div class="status-center">
      <div class="factions-display">
        <FactionBadge faction="institute" :value="gameState.factionReputation.institute" icon="🏛️" />
        <FactionBadge faction="clans" :value="gameState.factionReputation.clans" icon="🌲" />
        <FactionBadge faction="echoborn" :value="gameState.factionReputation.echoborn" icon="👻" />
      </div>
    </div>

    <div class="status-right">
      <div class="languages-display">
        <span v-for="lang in gameState.languagesKnown" :key="lang" class="lang-badge">
          🗣️ {{ lang }}
        </span>
        <span v-for="dialect in gameState.dialectsKnown" :key="dialect" class="dialect-badge">
          🔮 {{ dialect }}
        </span>
      </div>
      <div class="status-buttons">
        <button class="status-btn save-btn" title="Save Game" @click="emit('save')">
          💾
        </button>
        <button class="status-btn reset-btn" title="New Game" @click="emit('reset')">
          🔄
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { GameState } from '../types'
import FactionBadge from './FactionBadge.vue'

interface Props {
  gameState: GameState
  sceneName: string
}

defineProps<Props>()
const emit = defineEmits<{
  save: []
  reset: []
}>()

const formatLocation = (location: string): string => {
  return location
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}
</script>

<style src="./StatusBar.css"></style>

// game/src/components/StatusBar.tsx
// 📊 Status Bar Component ✨
import type { GameState } from '../types';
import './StatusBar.css';

interface StatusBarProps {
  gameState: GameState;
  sceneName: string;
  onSave: () => void;
  onReset: () => void;
}

export function StatusBar({ gameState, sceneName, onSave, onReset }: StatusBarProps) {
  const { factionReputation, languagesKnown, dialectsKnown, driftStability } = gameState;

  return (
    <div className="status-bar">
      <div className="status-left">
        <span className="location-badge">
          📍 {formatLocation(sceneName)}
        </span>
        <span className="stability-badge" style={{ 
          color: driftStability > 70 ? '#22c55e' : driftStability > 30 ? '#f59e0b' : '#ef4444' 
        }}>
          🌀 Drift: {driftStability}%
        </span>
      </div>
      
      <div className="status-center">
        <div className="factions-display">
          <FactionBadge faction="institute" value={factionReputation.institute} icon="🏛️" />
          <FactionBadge faction="clans" value={factionReputation.clans} icon="🌲" />
          <FactionBadge faction="echoborn" value={factionReputation.echoborn} icon="👻" />
        </div>
      </div>

      <div className="status-right">
        <div className="languages-display">
          {languagesKnown.map(lang => (
            <span key={lang} className="lang-badge">🗣️ {lang}</span>
          ))}
          {dialectsKnown.map(dialect => (
            <span key={dialect} className="dialect-badge">🔮 {dialect}</span>
          ))}
        </div>
        <div className="status-buttons">
          <button className="status-btn save-btn" onClick={onSave} title="Save Game">
            💾
          </button>
          <button className="status-btn reset-btn" onClick={onReset} title="New Game">
            🔄
          </button>
        </div>
      </div>
    </div>
  );
}

function FactionBadge({ faction, value, icon }: { faction: string; value: number; icon: string }) {
  const color = value > 20 ? '#22c55e' : value < -20 ? '#ef4444' : '#94a3b8';
  return (
    <span className="faction-badge" style={{ borderColor: color }} title={`${faction}: ${value}`}>
      {icon} {value > 0 ? '+' : ''}{value}
    </span>
  );
}

function formatLocation(location: string): string {
  return location
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
